
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Data.EntityClient
Imports System.ComponentModel
Imports System.Xml.Serialization
Imports System.Runtime.Serialization

<Assembly: EdmSchemaAttribute("c58c2ca8-3b6a-4e6f-99ef-8819781f8de8")>

#Region "Contexts"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
Public Partial Class CarsDBEntities
    Inherits ObjectContext

    #Region "Constructors"

    ''' <summary>
    ''' Initializes a new CarsDBEntities object using the connection string found in the 'CarsDBEntities' section of the application configuration file.
    ''' </summary>
    Public Sub New()
        MyBase.New("name=CarsDBEntities", "CarsDBEntities")
    MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new CarsDBEntities object.
    ''' </summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "CarsDBEntities")
    MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new CarsDBEntities object.
    ''' </summary>
    Public Sub New(ByVal connection As EntityConnection)
        MyBase.New(connection, "CarsDBEntities")
    MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    #End Region

    #Region "Partial Methods"

    Partial Private Sub OnContextCreated()
    End Sub

    #End Region

    #Region "ObjectSet Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property CarScheduling() As ObjectSet(Of CarScheduling)
        Get
            If (_CarScheduling Is Nothing) Then
                _CarScheduling = MyBase.CreateObjectSet(Of CarScheduling)("CarScheduling")
            End If
            Return _CarScheduling
        End Get
    End Property

    Private _CarScheduling As ObjectSet(Of CarScheduling)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Cars() As ObjectSet(Of Cars)
        Get
            If (_Cars Is Nothing) Then
                _Cars = MyBase.CreateObjectSet(Of Cars)("Cars")
            End If
            Return _Cars
        End Get
    End Property

    Private _Cars As ObjectSet(Of Cars)

    #End Region
    #Region "AddTo Methods"

    ''' <summary>
    ''' Deprecated Method for adding a new object to the CarScheduling EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToCarScheduling(ByVal carScheduling As CarScheduling)
        MyBase.AddObject("CarScheduling", carScheduling)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Cars EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToCars(ByVal cars As Cars)
        MyBase.AddObject("Cars", cars)
    End Sub

    #End Region
End Class

#End Region
#Region "Entities"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="CarsDBModel", Name:="Cars")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Cars
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new Cars object.
    ''' </summary>
    ''' <param name="id">Initial value of the ID property.</param>
    Public Shared Function CreateCars(id As Global.System.Int32) As Cars
        Dim cars as Cars = New Cars
        cars.ID = id
        Return cars
    End Function

    #End Region
    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property ID() As Global.System.Int32
        Get
            Return _ID
        End Get
        Set
            If (_ID <> Value) Then
                OnIDChanging(value)
                ReportPropertyChanging("ID")
                _ID = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("ID")
                OnIDChanged()
            End If
        End Set
    End Property

    Private _ID As Global.System.Int32
    Private Partial Sub OnIDChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnIDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Trademark() As Global.System.String
        Get
            Return _Trademark
        End Get
        Set
            OnTrademarkChanging(value)
            ReportPropertyChanging("Trademark")
            _Trademark = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Trademark")
            OnTrademarkChanged()
        End Set
    End Property

    Private _Trademark As Global.System.String
    Private Partial Sub OnTrademarkChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnTrademarkChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Model() As Global.System.String
        Get
            Return _Model
        End Get
        Set
            OnModelChanging(value)
            ReportPropertyChanging("Model")
            _Model = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Model")
            OnModelChanged()
        End Set
    End Property

    Private _Model As Global.System.String
    Private Partial Sub OnModelChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnModelChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property HP() As Nullable(Of Global.System.Int16)
        Get
            Return _HP
        End Get
        Set
            OnHPChanging(value)
            ReportPropertyChanging("HP")
            _HP = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("HP")
            OnHPChanged()
        End Set
    End Property

    Private _HP As Nullable(Of Global.System.Int16)
    Private Partial Sub OnHPChanging(value As Nullable(Of Global.System.Int16))
    End Sub

    Private Partial Sub OnHPChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Liter() As Nullable(Of Global.System.Double)
        Get
            Return _Liter
        End Get
        Set
            OnLiterChanging(value)
            ReportPropertyChanging("Liter")
            _Liter = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Liter")
            OnLiterChanged()
        End Set
    End Property

    Private _Liter As Nullable(Of Global.System.Double)
    Private Partial Sub OnLiterChanging(value As Nullable(Of Global.System.Double))
    End Sub

    Private Partial Sub OnLiterChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Cyl() As Nullable(Of Global.System.Byte)
        Get
            Return _Cyl
        End Get
        Set
            OnCylChanging(value)
            ReportPropertyChanging("Cyl")
            _Cyl = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Cyl")
            OnCylChanged()
        End Set
    End Property

    Private _Cyl As Nullable(Of Global.System.Byte)
    Private Partial Sub OnCylChanging(value As Nullable(Of Global.System.Byte))
    End Sub

    Private Partial Sub OnCylChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property TransmissSpeedCount() As Nullable(Of Global.System.Byte)
        Get
            Return _TransmissSpeedCount
        End Get
        Set
            OnTransmissSpeedCountChanging(value)
            ReportPropertyChanging("TransmissSpeedCount")
            _TransmissSpeedCount = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("TransmissSpeedCount")
            OnTransmissSpeedCountChanged()
        End Set
    End Property

    Private _TransmissSpeedCount As Nullable(Of Global.System.Byte)
    Private Partial Sub OnTransmissSpeedCountChanging(value As Nullable(Of Global.System.Byte))
    End Sub

    Private Partial Sub OnTransmissSpeedCountChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property TransmissAutomatic() As Global.System.String
        Get
            Return _TransmissAutomatic
        End Get
        Set
            OnTransmissAutomaticChanging(value)
            ReportPropertyChanging("TransmissAutomatic")
            _TransmissAutomatic = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("TransmissAutomatic")
            OnTransmissAutomaticChanged()
        End Set
    End Property

    Private _TransmissAutomatic As Global.System.String
    Private Partial Sub OnTransmissAutomaticChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnTransmissAutomaticChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property MPG_City() As Nullable(Of Global.System.Byte)
        Get
            Return _MPG_City
        End Get
        Set
            OnMPG_CityChanging(value)
            ReportPropertyChanging("MPG_City")
            _MPG_City = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("MPG_City")
            OnMPG_CityChanged()
        End Set
    End Property

    Private _MPG_City As Nullable(Of Global.System.Byte)
    Private Partial Sub OnMPG_CityChanging(value As Nullable(Of Global.System.Byte))
    End Sub

    Private Partial Sub OnMPG_CityChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property MPG_Highway() As Nullable(Of Global.System.Byte)
        Get
            Return _MPG_Highway
        End Get
        Set
            OnMPG_HighwayChanging(value)
            ReportPropertyChanging("MPG_Highway")
            _MPG_Highway = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("MPG_Highway")
            OnMPG_HighwayChanged()
        End Set
    End Property

    Private _MPG_Highway As Nullable(Of Global.System.Byte)
    Private Partial Sub OnMPG_HighwayChanging(value As Nullable(Of Global.System.Byte))
    End Sub

    Private Partial Sub OnMPG_HighwayChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Category() As Global.System.String
        Get
            Return _Category
        End Get
        Set
            OnCategoryChanging(value)
            ReportPropertyChanging("Category")
            _Category = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Category")
            OnCategoryChanged()
        End Set
    End Property

    Private _Category As Global.System.String
    Private Partial Sub OnCategoryChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnCategoryChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Description() As Global.System.String
        Get
            Return _Description
        End Get
        Set
            OnDescriptionChanging(value)
            ReportPropertyChanging("Description")
            _Description = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Description")
            OnDescriptionChanged()
        End Set
    End Property

    Private _Description As Global.System.String
    Private Partial Sub OnDescriptionChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnDescriptionChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Hyperlink() As Global.System.String
        Get
            Return _Hyperlink
        End Get
        Set
            OnHyperlinkChanging(value)
            ReportPropertyChanging("Hyperlink")
            _Hyperlink = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Hyperlink")
            OnHyperlinkChanged()
        End Set
    End Property

    Private _Hyperlink As Global.System.String
    Private Partial Sub OnHyperlinkChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnHyperlinkChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Picture() As Global.System.Byte()
        Get
                Return StructuralObject.GetValidValue(_Picture)
        End Get
        Set
            OnPictureChanging(value)
            ReportPropertyChanging("Picture")
            _Picture = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Picture")
            OnPictureChanged()
        End Set
    End Property

    Private _Picture As Global.System.Byte()
    Private Partial Sub OnPictureChanging(value As Global.System.Byte())
    End Sub

    Private Partial Sub OnPictureChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Price() As Nullable(Of Global.System.Decimal)
        Get
            Return _Price
        End Get
        Set
            OnPriceChanging(value)
            ReportPropertyChanging("Price")
            _Price = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Price")
            OnPriceChanged()
        End Set
    End Property

    Private _Price As Nullable(Of Global.System.Decimal)
    Private Partial Sub OnPriceChanging(value As Nullable(Of Global.System.Decimal))
    End Sub

    Private Partial Sub OnPriceChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property RtfContent() As Global.System.String
        Get
            Return _RtfContent
        End Get
        Set
            OnRtfContentChanging(value)
            ReportPropertyChanging("RtfContent")
            _RtfContent = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("RtfContent")
            OnRtfContentChanged()
        End Set
    End Property

    Private _RtfContent As Global.System.String
    Private Partial Sub OnRtfContentChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnRtfContentChanged()
    End Sub

    #End Region
End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="CarsDBModel", Name:="CarScheduling")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class CarScheduling
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new CarScheduling object.
    ''' </summary>
    ''' <param name="id">Initial value of the ID property.</param>
    ''' <param name="allDay">Initial value of the AllDay property.</param>
    Public Shared Function CreateCarScheduling(id As Global.System.Int32, allDay As Global.System.Boolean) As CarScheduling
        Dim carScheduling as CarScheduling = New CarScheduling
        carScheduling.ID = id
        carScheduling.AllDay = allDay
        Return carScheduling
    End Function

    #End Region
    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property ID() As Global.System.Int32
        Get
            Return _ID
        End Get
        Set
            If (_ID <> Value) Then
                OnIDChanging(value)
                ReportPropertyChanging("ID")
                _ID = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("ID")
                OnIDChanged()
            End If
        End Set
    End Property

    Private _ID As Global.System.Int32
    Private Partial Sub OnIDChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnIDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property CarId() As Nullable(Of Global.System.Int32)
        Get
            Return _CarId
        End Get
        Set
            OnCarIdChanging(value)
            ReportPropertyChanging("CarId")
            _CarId = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("CarId")
            OnCarIdChanged()
        End Set
    End Property

    Private _CarId As Nullable(Of Global.System.Int32)
    Private Partial Sub OnCarIdChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnCarIdChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property UserId() As Nullable(Of Global.System.Int32)
        Get
            Return _UserId
        End Get
        Set
            OnUserIdChanging(value)
            ReportPropertyChanging("UserId")
            _UserId = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("UserId")
            OnUserIdChanged()
        End Set
    End Property

    Private _UserId As Nullable(Of Global.System.Int32)
    Private Partial Sub OnUserIdChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnUserIdChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Status() As Nullable(Of Global.System.Int32)
        Get
            Return _Status
        End Get
        Set
            OnStatusChanging(value)
            ReportPropertyChanging("Status")
            _Status = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Status")
            OnStatusChanged()
        End Set
    End Property

    Private _Status As Nullable(Of Global.System.Int32)
    Private Partial Sub OnStatusChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnStatusChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Subject() As Global.System.String
        Get
            Return _Subject
        End Get
        Set
            OnSubjectChanging(value)
            ReportPropertyChanging("Subject")
            _Subject = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Subject")
            OnSubjectChanged()
        End Set
    End Property

    Private _Subject As Global.System.String
    Private Partial Sub OnSubjectChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnSubjectChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Description() As Global.System.String
        Get
            Return _Description
        End Get
        Set
            OnDescriptionChanging(value)
            ReportPropertyChanging("Description")
            _Description = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Description")
            OnDescriptionChanged()
        End Set
    End Property

    Private _Description As Global.System.String
    Private Partial Sub OnDescriptionChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnDescriptionChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Label() As Nullable(Of Global.System.Int32)
        Get
            Return _Label
        End Get
        Set
            OnLabelChanging(value)
            ReportPropertyChanging("Label")
            _Label = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Label")
            OnLabelChanged()
        End Set
    End Property

    Private _Label As Nullable(Of Global.System.Int32)
    Private Partial Sub OnLabelChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnLabelChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property StartTime() As Nullable(Of Global.System.DateTime)
        Get
            Return _StartTime
        End Get
        Set
            OnStartTimeChanging(value)
            ReportPropertyChanging("StartTime")
            _StartTime = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("StartTime")
            OnStartTimeChanged()
        End Set
    End Property

    Private _StartTime As Nullable(Of Global.System.DateTime)
    Private Partial Sub OnStartTimeChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub OnStartTimeChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property EndTime() As Nullable(Of Global.System.DateTime)
        Get
            Return _EndTime
        End Get
        Set
            OnEndTimeChanging(value)
            ReportPropertyChanging("EndTime")
            _EndTime = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("EndTime")
            OnEndTimeChanged()
        End Set
    End Property

    Private _EndTime As Nullable(Of Global.System.DateTime)
    Private Partial Sub OnEndTimeChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub OnEndTimeChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Location() As Global.System.String
        Get
            Return _Location
        End Get
        Set
            OnLocationChanging(value)
            ReportPropertyChanging("Location")
            _Location = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Location")
            OnLocationChanged()
        End Set
    End Property

    Private _Location As Global.System.String
    Private Partial Sub OnLocationChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnLocationChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property AllDay() As Global.System.Boolean
        Get
            Return _AllDay
        End Get
        Set
            OnAllDayChanging(value)
            ReportPropertyChanging("AllDay")
            _AllDay = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("AllDay")
            OnAllDayChanged()
        End Set
    End Property

    Private _AllDay As Global.System.Boolean
    Private Partial Sub OnAllDayChanging(value As Global.System.Boolean)
    End Sub

    Private Partial Sub OnAllDayChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property EventType() As Nullable(Of Global.System.Int32)
        Get
            Return _EventType
        End Get
        Set
            OnEventTypeChanging(value)
            ReportPropertyChanging("EventType")
            _EventType = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("EventType")
            OnEventTypeChanged()
        End Set
    End Property

    Private _EventType As Nullable(Of Global.System.Int32)
    Private Partial Sub OnEventTypeChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnEventTypeChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property RecurrenceInfo() As Global.System.String
        Get
            Return _RecurrenceInfo
        End Get
        Set
            OnRecurrenceInfoChanging(value)
            ReportPropertyChanging("RecurrenceInfo")
            _RecurrenceInfo = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("RecurrenceInfo")
            OnRecurrenceInfoChanged()
        End Set
    End Property

    Private _RecurrenceInfo As Global.System.String
    Private Partial Sub OnRecurrenceInfoChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnRecurrenceInfoChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property ReminderInfo() As Global.System.String
        Get
            Return _ReminderInfo
        End Get
        Set
            OnReminderInfoChanging(value)
            ReportPropertyChanging("ReminderInfo")
            _ReminderInfo = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("ReminderInfo")
            OnReminderInfoChanged()
        End Set
    End Property

    Private _ReminderInfo As Global.System.String
    Private Partial Sub OnReminderInfoChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnReminderInfoChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Price() As Nullable(Of Global.System.Decimal)
        Get
            Return _Price
        End Get
        Set
            OnPriceChanging(value)
            ReportPropertyChanging("Price")
            _Price = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Price")
            OnPriceChanged()
        End Set
    End Property

    Private _Price As Nullable(Of Global.System.Decimal)
    Private Partial Sub OnPriceChanging(value As Nullable(Of Global.System.Decimal))
    End Sub

    Private Partial Sub OnPriceChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property ContactInfo() As Global.System.String
        Get
            Return _ContactInfo
        End Get
        Set
            OnContactInfoChanging(value)
            ReportPropertyChanging("ContactInfo")
            _ContactInfo = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("ContactInfo")
            OnContactInfoChanged()
        End Set
    End Property

    Private _ContactInfo As Global.System.String
    Private Partial Sub OnContactInfoChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnContactInfoChanged()
    End Sub

    #End Region
End Class

#End Region

